# Generated by Django 3.0.5 on 2021-01-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chat_hash',
            field=models.CharField(default='x3xcMrsky3Z9IyM1cU1kobaY8xqQEinF', max_length=32),
        ),
    ]
