# Generated by Django 3.0.5 on 2021-01-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_account_chat_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='chat_hash',
            field=models.TextField(default='dfc78073611b11ebab36d050999d14ce'),
        ),
    ]
