# Generated by Django 3.0.5 on 2021-01-28 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210128_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='chat_hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
